# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tree.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tree.proto',
  package='protoTrees',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ntree.proto\x12\nprotoTrees\"#\n\x0bTreeRequest\x12\x0e\n\x01n\x18\x01 \x01(\x05H\x00\x88\x01\x01\x42\x04\n\x02_n\"\xb4\x04\n\x04Tree\x12\x0f\n\x02id\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x15\n\x08latitude\x18\x02 \x01(\x01H\x01\x88\x01\x01\x12\x16\n\tlongitude\x18\x03 \x01(\x01H\x02\x88\x01\x01\x12\x19\n\x0cSoortnaam_NL\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x1a\n\rSoortnaam_WTS\x18\x05 \x01(\tH\x04\x88\x01\x01\x12\x15\n\x08\x42oomtype\x18\x06 \x01(\tH\x05\x88\x01\x01\x12\x17\n\nBoomhoogte\x18\x07 \x01(\tH\x06\x88\x01\x01\x12\x16\n\tPlantjaar\x18\x08 \x01(\x05H\x07\x88\x01\x01\x12\x15\n\x08\x45igenaar\x18\t \x01(\tH\x08\x88\x01\x01\x12\x16\n\tBeheerder\x18\n \x01(\tH\t\x88\x01\x01\x12\x16\n\tCategorie\x18\x0b \x01(\tH\n\x88\x01\x01\x12\x17\n\nBoomnummer\x18\x0c \x01(\x05H\x0b\x88\x01\x01\x12\x17\n\nSOORT_KORT\x18\r \x01(\tH\x0c\x88\x01\x01\x12\x13\n\x06SDVIEW\x18\x0e \x01(\tH\r\x88\x01\x01\x12\x13\n\x06RADIUS\x18\x0f \x01(\x05H\x0e\x88\x01\x01\x42\x05\n\x03_idB\x0b\n\t_latitudeB\x0c\n\n_longitudeB\x0f\n\r_Soortnaam_NLB\x10\n\x0e_Soortnaam_WTSB\x0b\n\t_BoomtypeB\r\n\x0b_BoomhoogteB\x0c\n\n_PlantjaarB\x0b\n\t_EigenaarB\x0c\n\n_BeheerderB\x0c\n\n_CategorieB\r\n\x0b_BoomnummerB\r\n\x0b_SOORT_KORTB\t\n\x07_SDVIEWB\t\n\x07_RADIUS2F\n\x0bTreeService\x12\x37\n\x08getTrees\x12\x17.protoTrees.TreeRequest\x1a\x10.protoTrees.Tree\"\x00\x62\x06proto3'
)




_TREEREQUEST = _descriptor.Descriptor(
  name='TreeRequest',
  full_name='protoTrees.TreeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='n', full_name='protoTrees.TreeRequest.n', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_n', full_name='protoTrees.TreeRequest._n',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=26,
  serialized_end=61,
)


_TREE = _descriptor.Descriptor(
  name='Tree',
  full_name='protoTrees.Tree',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='protoTrees.Tree.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='protoTrees.Tree.latitude', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='protoTrees.Tree.longitude', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Soortnaam_NL', full_name='protoTrees.Tree.Soortnaam_NL', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Soortnaam_WTS', full_name='protoTrees.Tree.Soortnaam_WTS', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Boomtype', full_name='protoTrees.Tree.Boomtype', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Boomhoogte', full_name='protoTrees.Tree.Boomhoogte', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Plantjaar', full_name='protoTrees.Tree.Plantjaar', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Eigenaar', full_name='protoTrees.Tree.Eigenaar', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Beheerder', full_name='protoTrees.Tree.Beheerder', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Categorie', full_name='protoTrees.Tree.Categorie', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Boomnummer', full_name='protoTrees.Tree.Boomnummer', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='SOORT_KORT', full_name='protoTrees.Tree.SOORT_KORT', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='SDVIEW', full_name='protoTrees.Tree.SDVIEW', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='RADIUS', full_name='protoTrees.Tree.RADIUS', index=14,
      number=15, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_id', full_name='protoTrees.Tree._id',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_latitude', full_name='protoTrees.Tree._latitude',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_longitude', full_name='protoTrees.Tree._longitude',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_Soortnaam_NL', full_name='protoTrees.Tree._Soortnaam_NL',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_Soortnaam_WTS', full_name='protoTrees.Tree._Soortnaam_WTS',
      index=4, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_Boomtype', full_name='protoTrees.Tree._Boomtype',
      index=5, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_Boomhoogte', full_name='protoTrees.Tree._Boomhoogte',
      index=6, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_Plantjaar', full_name='protoTrees.Tree._Plantjaar',
      index=7, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_Eigenaar', full_name='protoTrees.Tree._Eigenaar',
      index=8, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_Beheerder', full_name='protoTrees.Tree._Beheerder',
      index=9, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_Categorie', full_name='protoTrees.Tree._Categorie',
      index=10, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_Boomnummer', full_name='protoTrees.Tree._Boomnummer',
      index=11, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_SOORT_KORT', full_name='protoTrees.Tree._SOORT_KORT',
      index=12, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_SDVIEW', full_name='protoTrees.Tree._SDVIEW',
      index=13, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_RADIUS', full_name='protoTrees.Tree._RADIUS',
      index=14, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=64,
  serialized_end=628,
)

_TREEREQUEST.oneofs_by_name['_n'].fields.append(
  _TREEREQUEST.fields_by_name['n'])
_TREEREQUEST.fields_by_name['n'].containing_oneof = _TREEREQUEST.oneofs_by_name['_n']
_TREE.oneofs_by_name['_id'].fields.append(
  _TREE.fields_by_name['id'])
_TREE.fields_by_name['id'].containing_oneof = _TREE.oneofs_by_name['_id']
_TREE.oneofs_by_name['_latitude'].fields.append(
  _TREE.fields_by_name['latitude'])
_TREE.fields_by_name['latitude'].containing_oneof = _TREE.oneofs_by_name['_latitude']
_TREE.oneofs_by_name['_longitude'].fields.append(
  _TREE.fields_by_name['longitude'])
_TREE.fields_by_name['longitude'].containing_oneof = _TREE.oneofs_by_name['_longitude']
_TREE.oneofs_by_name['_Soortnaam_NL'].fields.append(
  _TREE.fields_by_name['Soortnaam_NL'])
_TREE.fields_by_name['Soortnaam_NL'].containing_oneof = _TREE.oneofs_by_name['_Soortnaam_NL']
_TREE.oneofs_by_name['_Soortnaam_WTS'].fields.append(
  _TREE.fields_by_name['Soortnaam_WTS'])
_TREE.fields_by_name['Soortnaam_WTS'].containing_oneof = _TREE.oneofs_by_name['_Soortnaam_WTS']
_TREE.oneofs_by_name['_Boomtype'].fields.append(
  _TREE.fields_by_name['Boomtype'])
_TREE.fields_by_name['Boomtype'].containing_oneof = _TREE.oneofs_by_name['_Boomtype']
_TREE.oneofs_by_name['_Boomhoogte'].fields.append(
  _TREE.fields_by_name['Boomhoogte'])
_TREE.fields_by_name['Boomhoogte'].containing_oneof = _TREE.oneofs_by_name['_Boomhoogte']
_TREE.oneofs_by_name['_Plantjaar'].fields.append(
  _TREE.fields_by_name['Plantjaar'])
_TREE.fields_by_name['Plantjaar'].containing_oneof = _TREE.oneofs_by_name['_Plantjaar']
_TREE.oneofs_by_name['_Eigenaar'].fields.append(
  _TREE.fields_by_name['Eigenaar'])
_TREE.fields_by_name['Eigenaar'].containing_oneof = _TREE.oneofs_by_name['_Eigenaar']
_TREE.oneofs_by_name['_Beheerder'].fields.append(
  _TREE.fields_by_name['Beheerder'])
_TREE.fields_by_name['Beheerder'].containing_oneof = _TREE.oneofs_by_name['_Beheerder']
_TREE.oneofs_by_name['_Categorie'].fields.append(
  _TREE.fields_by_name['Categorie'])
_TREE.fields_by_name['Categorie'].containing_oneof = _TREE.oneofs_by_name['_Categorie']
_TREE.oneofs_by_name['_Boomnummer'].fields.append(
  _TREE.fields_by_name['Boomnummer'])
_TREE.fields_by_name['Boomnummer'].containing_oneof = _TREE.oneofs_by_name['_Boomnummer']
_TREE.oneofs_by_name['_SOORT_KORT'].fields.append(
  _TREE.fields_by_name['SOORT_KORT'])
_TREE.fields_by_name['SOORT_KORT'].containing_oneof = _TREE.oneofs_by_name['_SOORT_KORT']
_TREE.oneofs_by_name['_SDVIEW'].fields.append(
  _TREE.fields_by_name['SDVIEW'])
_TREE.fields_by_name['SDVIEW'].containing_oneof = _TREE.oneofs_by_name['_SDVIEW']
_TREE.oneofs_by_name['_RADIUS'].fields.append(
  _TREE.fields_by_name['RADIUS'])
_TREE.fields_by_name['RADIUS'].containing_oneof = _TREE.oneofs_by_name['_RADIUS']
DESCRIPTOR.message_types_by_name['TreeRequest'] = _TREEREQUEST
DESCRIPTOR.message_types_by_name['Tree'] = _TREE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TreeRequest = _reflection.GeneratedProtocolMessageType('TreeRequest', (_message.Message,), {
  'DESCRIPTOR' : _TREEREQUEST,
  '__module__' : 'tree_pb2'
  # @@protoc_insertion_point(class_scope:protoTrees.TreeRequest)
  })
_sym_db.RegisterMessage(TreeRequest)

Tree = _reflection.GeneratedProtocolMessageType('Tree', (_message.Message,), {
  'DESCRIPTOR' : _TREE,
  '__module__' : 'tree_pb2'
  # @@protoc_insertion_point(class_scope:protoTrees.Tree)
  })
_sym_db.RegisterMessage(Tree)



_TREESERVICE = _descriptor.ServiceDescriptor(
  name='TreeService',
  full_name='protoTrees.TreeService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=630,
  serialized_end=700,
  methods=[
  _descriptor.MethodDescriptor(
    name='getTrees',
    full_name='protoTrees.TreeService.getTrees',
    index=0,
    containing_service=None,
    input_type=_TREEREQUEST,
    output_type=_TREE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TREESERVICE)

DESCRIPTOR.services_by_name['TreeService'] = _TREESERVICE

# @@protoc_insertion_point(module_scope)
